// <auto-generated />
using api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace api.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	partial class ApplicationDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
					.HasAnnotation("ProductVersion", "3.1.3")
					.HasAnnotation("Relational:MaxIdentifierLength", 63);

			modelBuilder.Entity("api.Models.movieList", b =>
					{
						b.Property<int>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("integer")
											.HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

						b.Property<string>("MovieName")
											.IsRequired()
											.HasColumnType("text");

						b.Property<int>("Rating")
											.HasColumnType("integer");

						b.Property<int>("ReleaseDate")
											.HasColumnType("integer");

						b.HasKey("Id");

						b.ToTable("movieList");
					});
#pragma warning restore 612, 618
		}
	}
}
